export const FILLER_WORDS = new Set([
  "the", "a", "an", "and", "or", "but", "in", "on", "at", "to", "for",
  "of", "with", "by", "from", "is", "was", "are", "were", "be", "been",
  "being", "have", "has", "had", "do", "does", "did", "will", "would",
  "could", "should", "may", "might", "must", "shall", "can", "need",
  "this", "that", "these", "those", "i", "me", "my", "we", "us", "our",
  "you", "your", "he", "him", "his", "she", "her", "it", "its", "they",
  "them", "their", "what", "which", "who", "when", "where", "why", "how",
  "all", "each", "every", "both", "few", "more", "most", "other", "some",
  "such", "no", "nor", "not", "only", "own", "same", "so", "than", "too",
  "very", "just", "also", "as", "if", "about", "into", "through", "during",
  "before", "after", "above", "below", "up", "down", "out", "off", "over",
  "under", "again", "further", "here", "there", "now", "then", "any",
]);

export const SKILL_ALIASES: Record<string, string> = {
  "js": "javascript", "ts": "typescript", "py": "python",
  "reactjs": "react", "react.js": "react", "nextjs": "next.js", "next.js": "next.js",
  "nodejs": "node.js", "node.js": "node.js", "node": "node.js",
  "expressjs": "express", "express.js": "express",
  "django": "django", "flask": "flask", "fastapi": "fastapi",
  "springboot": "spring boot", "spring-boot": "spring boot",
  "postgres": "postgresql", "pg": "postgresql",
  "mongo": "mongodb", "redis cache": "redis",
  "k8s": "kubernetes", "docker containers": "docker",
  "aws s3": "aws", "ec2": "aws", "lambda": "aws",
  "gcp": "google cloud", "gke": "google cloud",
  "azure devops": "azure",
  "ci/cd": "ci cd", "ci-cd": "ci cd",
  "ml": "machine learning", "ai": "artificial intelligence",
  "nlp": "natural language processing",
  "dl": "deep learning", "nn": "neural networks",
  "cnn": "convolutional neural networks", "rnn": "recurrent neural networks",
  "tensorflow": "tensorflow", "tf": "tensorflow",
  "pytorch": "pytorch", "keras": "keras",
  "tableau": "tableau", "powerbi": "power bi", "power bi": "power bi",
  "excel": "microsoft excel", "ms excel": "microsoft excel",
  "powerpoint": "microsoft powerpoint", "ms powerpoint": "microsoft powerpoint",
  "word": "microsoft word", "ms word": "microsoft word",
  "c++": "c++", "cpp": "c++", "c language": "c",
  "c#": "c#", "csharp": "c#", ".net": ".net", "dotnet": ".net",
  "java ee": "java ee", "j2ee": "java ee",
  "html5": "html", "html5/css3": "html",
  "css3": "css", "tailwind": "tailwind css",
  "sass": "sass", "scss": "sass",
  "bootstrap": "bootstrap", "material ui": "material ui", "mui": "material ui",
  "graphql": "graphql", "gql": "graphql",
  "rest api": "rest api", "restful": "rest api",
  "etl": "etl", "ssis": "ssis", "ssrs": "ssrs", "ssas": "ssas",
  "sap abap": "sap abap", "sap hana": "sap hana", "sap fico": "sap fico",
  "sap mm": "sap mm", "sap sd": "sap sd", "sap pp": "sap pp",
  "autocad": "autocad", "solidworks": "solidworks", "catia": "catia",
  "ansys": "ansys", "matlab": "matlab", "labview": "labview",
  "verilog": "verilog", "vhdl": "vhdl", "fpga": "fpga",
  "arm": "arm", "arduino": "arduino", "raspberry pi": "raspberry pi",
  "iot": "internet of things", "embedded c": "embedded c",
  "staad": "staad pro", "staad.pro": "staad pro",
  "primavera": "primavera", "ms project": "microsoft project",
  "tally": "tally", "quickbooks": "quickbooks",
  "gst": "gst", "income tax": "income tax",
  "payroll": "payroll", "recruitment": "recruitment",
  "onboarding": "onboarding", "employee engagement": "employee engagement",
  "performance management": "performance management",
  "leadership": "leadership", "team management": "team management",
  "project management": "project management", "pmp": "pmp",
  "agile": "agile", "scrum": "scrum", "kanban": "kanban",
  "jira": "jira", "confluence": "confluence",
};

export const DOMAIN_SKILLS: Record<string, string[]> = {
  cse: [
    "python", "java", "c++", "c", "c#", "javascript", "typescript", "go", "rust",
    "data structures", "algorithms", "operating systems", "computer networks",
    "dbms", "oops", "compiler design", "theory of computation",
    "machine learning", "artificial intelligence", "deep learning",
    "natural language processing", "computer vision",
    "tensorflow", "pytorch", "keras", "scikit-learn",
    "html", "css", "react", "angular", "vue", "node.js", "express",
    "django", "flask", "fastapi", "spring boot",
    "postgresql", "mongodb", "mysql", "redis", "elasticsearch",
    "docker", "kubernetes", "aws", "google cloud", "azure",
    "git", "ci cd", "rest api", "graphql", "microservices",
  ],
  it_services: [
    "java", "spring boot", ".net", "c#", "sql server", "oracle",
    "sap abap", "sap hana", "sap fico", "sap mm", "sap sd",
    "service now", "salesforce", "workday",
    "etl", "informatica", "data warehousing",
    "testing", "selenium", "junit", "testng", "cypress",
    "jira", "confluence", "agile", "scrum",
    "python", "sql", "tableau", "power bi",
    "linux", "shell scripting", "ansible", "terraform",
  ],
  ece_eee: [
    "embedded systems", "verilog", "vhdl", "fpga", "arduino",
    "raspberry pi", "stm32", "arm", "pic microcontroller",
    "matlab", "simulink", "labview", "proteus",
    "circuit design", "pcb design", "signal processing",
    "vlsi", "analog circuits", "digital circuits",
    "communication systems", "antenna design", "rf design",
    "iot", "sensors", "actuators", "embedded c",
    "power electronics", "power systems", "control systems",
  ],
  mechanical: [
    "autocad", "solidworks", "catia", "creo", "ansys", "abaqus",
    "hypermesh", "gd&t", "dfma", "fea", "cfd",
    "heat transfer", "thermodynamics", "fluid mechanics",
    "manufacturing", "cnc programming", "cam",
    "quality control", "six sigma", "lean manufacturing",
    "hydraulics", "pneumatics", "hvac", "automotive",
    "robotics", "mechatronics", "product design",
  ],
  civil: [
    "autocad", "staad pro", "primavera", "ms project",
    "revit", "bim", "civil 3d", "etabs", "sap2000",
    "structural design", "reinforced concrete", "steel design",
    "geotechnical engineering", "surveying", "estimation",
    "project management", "construction management",
    "highway engineering", "transportation engineering",
    "water resources", "environmental engineering",
  ],
  sap_erp: [
    "sap abap", "sap hana", "sap fico", "sap mm", "sap sd",
    "sap pp", "sap hr", "sap basis", "sap security",
    "sap pi po", "sap ui5", "sap fiori",
    "oracle apps", "oracle ebs", "peoplesoft",
    "workday", "service now",
  ],
  finance: [
    "financial analysis", "financial modeling", "valuation",
    "dcf", "npv", "irr", "excel modeling",
    "equity research", "credit analysis", "risk management",
    "portfolio management", "investment banking",
    "corporate finance", "treasury", "working capital",
    "gst", "income tax", "direct tax", "indirect tax",
    "auditing", "internal audit", "external audit",
    "tally", "quickbooks", "sap fico",
    "excel", "power bi", "tableau",
  ],
  banking_fintech: [
    "core banking", "retail banking", "corporate banking",
    "credit analysis", "risk assessment", "loan processing",
    "kyc", "aml", "fraud detection",
    "payment systems", "upi", "neft", "rtgs", "swift",
    "blockchain", "cryptocurrency", "smart contracts",
    "fintech", "digital lending", "nbfc",
    "nlp", "machine learning", "python", "sql",
  ],
  hr: [
    "recruitment", "sourcing", "screening", "interviewing",
    "onboarding", "induction", "orientation",
    "performance management", "appraisals",
    "employee engagement", "retention",
    "payroll", "compensation benefits",
    "statutory compliance", "pf", "esi", "gratuity",
    "hris", "sap hr", "workday",
    "training development", "ld",
    "organization development", "change management",
    "grievance handling", "labor laws",
  ],
  healthcare: [
    "medical coding", "medical billing", "icd 10", "cpt",
    "hipaa", "ehr", "emr", "epic", "cerner",
    "clinical research", "pharmacovigilance",
    "data entry", "healthcare analytics",
    "python", "sql", "tableau",
    "nursing", "patient care", "clinical data management",
  ],
  design: [
    "photoshop", "illustrator", "indesign", "figma",
    "sketch", "adobe xd", "canva", "coreldraw",
    "after effects", "premiere pro",
    "ui ux design", "wireframing", "prototyping",
    "user research", "usability testing",
    "design systems", "typography", "color theory",
    "graphic design", "brand identity", "logo design",
  ],
  business: [
    "business analysis", "requirements gathering",
    "stakeholder management", "process improvement",
    "lean", "six sigma", "root cause analysis",
    "data analysis", "excel", "sql", "tableau", "power bi",
    "project management", "agile", "scrum", "pmp",
    "presentation", "communication", "negotiation",
    "strategy", "market research", "competitive analysis",
    "sales", "crm", "lead generation",
  ],
  commerce: [
    "accounting", "bookkeeping", "tally", "quickbooks",
    "gst", "income tax", "auditing",
    "financial accounting", "management accounting",
    "cost accounting", "taxation",
    "excel", "financial modeling",
    "banking", "insurance", "investment",
    "business law", "company law",
  ],
  mba: [
    "strategy", "business development", "market research",
    "financial analysis", "investment analysis",
    "project management", "operations management",
    "supply chain", "logistics",
    "marketing", "digital marketing", "brand management",
    "sales management", "crm",
    "hr management", "organizational behavior",
    "leadership", "negotiation", "presentation",
    "consulting", "problem solving", "case study",
  ],
  general: [
    "communication", "teamwork", "leadership",
    "problem solving", "time management", "analytical skills",
    "presentation", "writing", "creativity",
    "adaptability", "initiative", "hardworking",
  ],
};

export const SKILL_CATEGORY_WEIGHTS: Record<string, number> = {
  programming: 1.2,
  web_frameworks: 1.1,
  databases: 1.0,
  cloud_devops: 1.1,
  ml_ai: 1.15,
  soft_skills: 0.8,
  tools: 0.9,
  domain_specific: 1.0,
};

export const ACTION_VERBS = new Set([
  "developed", "designed", "built", "created", "implemented", "managed",
  "led", "launched", "optimized", "improved", "achieved", "delivered",
  "architected", "engineered", "established", "executed", "increased",
  "reduced", "analyzed", "automated", "configured", "deployed", "maintained",
  "monitored", "coordinated", "facilitated", "negotiated", "presented",
  "published", "researched", "streamlined", "supervised", "trained",
  "collaborated", "spearheaded", "pioneered", "transformed", "accelerated",
  "solved", "investigated", "tested", "migrated", "integrated",
]);

export const INDIAN_CERT_PATTERNS: { regex: RegExp; tier: number; label: string }[] = [
  { regex: /(?:iit|indian institute of technology)/i, tier: 5, label: "IIT" },
  { regex: /(?:iim|indian institute of management)/i, tier: 5, label: "IIM" },
  { regex: /(?:iisc|indian institute of science)/i, tier: 5, label: "IISc" },
  { regex: /(?:bits\s*pilani|birla institute)/i, tier: 4, label: "BITS Pilani" },
  { regex: /(?:nit|national institute of technology)/i, tier: 4, label: "NIT" },
  { regex: /(?:iiit|indian institute of information technology)/i, tier: 4, label: "IIIT" },
  { regex: /(?:isb|indian school of business)/i, tier: 5, label: "ISB" },
  { regex: /(?:bits|goa|hyderabad)/i, tier: 3, label: "BITS" },
  { regex: /(?:vit|vellore)/i, tier: 3, label: "VIT" },
  { regex: /(?:srm|chennai)/i, tier: 3, label: "SRM" },
  { regex: /(?:amrita|coimbatore)/i, tier: 3, label: "Amrita" },
  { regex: /(?:anna university)/i, tier: 3, label: "Anna University" },
  { regex: /(?:delhi university|du)/i, tier: 3, label: "DU" },
  { regex: /(?:mumbai university)/i, tier: 2, label: "Mumbai University" },
  { regex: /(?:pune university)/i, tier: 2, label: "Pune University" },
  { regex: /(?:jntu|jawaharlal nehru technological)/i, tier: 3, label: "JNTU" },
  { regex: /(?:b\.?tech|bachelor of technology)/i, tier: 2, label: "B.Tech" },
  { regex: /(?:m\.?tech|master of technology)/i, tier: 3, label: "M.Tech" },
  { regex: /(?:mba|master of business administration)/i, tier: 3, label: "MBA" },
  { regex: /(?:b\.?com|bachelor of commerce)/i, tier: 1, label: "B.Com" },
  { regex: /(?:b\.?sc|bachelor of science)/i, tier: 1, label: "B.Sc" },
  { regex: /(?:m\.?ca|master of computer applications)/i, tier: 2, label: "MCA" },
  { regex: /(?:b\.?e|bachelor of engineering)/i, tier: 2, label: "BE" },
  { regex: /(?:ph\.?d|doctorate)/i, tier: 4, label: "PhD" },
];

export const INDIAN_COMPANIES = [
  "tcs", "infosys", "wipro", "hcl", "tech mahindra", "cognizant",
  "accenture", "capgemini", "ibm", "microsoft", "google", "amazon",
  "flipkart", "snapdeal", "paytm", "swiggy", "zomato", "ola",
  "ril", "tata", "adani", "l&t", "larsen", "mahindra", "maruti",
];
